server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: customer-service
          uri: http://localhost:8081/
          predicates:
            - Path=/api/v1/customers/**
        - id: fraud
          uri: http://localhost:8082/
          predicates:
            - Path=/api/v1/fraud-check/**
  config:
    import: "optional:configserver:${CONFIG_URI:http://localhost:8888}"

