server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: customer-service
          uri: http://localhost:8081/
          predicates:
            - Path=/api/v1/customers/**
        - id: fraud
          uri: lb://fraud
          predicates:
            - Path=/api/v1/frauds/**
  config:
    import: "optional:configserver:${CONFIG_URI:http://localhost:8888}"

